[tool.poetry]
name = "research-aggregator-mcp"
version = "0.0.1"
description = ""
authors = ["Dan Madeira <dan.madeira@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
